### PR TITLE
fix(tsconfig.json): 🔧 cannot find module $lib in VS Code

### PR DESCRIPTION
**Pull request by wingstako**
Fix the error shown in the screenshot.

### CODE REVIEW

**Comment by kwaa** [comment]
This part added by this PR should be in `.svelte-kit/tsconfig.json` and I'm not sure why this is an issue.

```json
{
	"compilerOptions": {
		"baseUrl": "..",
		"paths": {
			"$lib": [
				"src/lib"
			],
			"$lib/*": [
				"src/lib/*"
			]
		},
		"rootDirs": [
			"..",
			"./types"
		],
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true,
		"lib": [
			"esnext",
			"DOM"
		],
		"moduleResolution": "node",
		"module": "esnext",
		"target": "esnext"
	},
	"include": [
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"./**"
	]
}
```

**Comment by kwaa** [comment]
🤔 So include doesn't automatically merge with extends?

**Comment by wingstako** [comment]
My bad. I did not notice the extension. I guess my VS Code cannot recognise the extended config

**Comment by wingstako** [comment]
I am looking for another way to solve this 😢

**Pull request closed without merging**
