### PR TITLE
Fix broken netlify build due to array.at()

### LINKED ISSUE #6: Demo site is down
https://urara-docs.netlify.app is no longer reachable. Caught in [`awesome-svelte-kit` CI](https://github.com/janosh/awesome-svelte-kit/runs/5367836902?check_suite_focus=true#step:4:187).

### PR DESCRIPTION
**Pull request by janosh**
If the build was only failing due to using `array.at()` which was [added in node v16.6.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility), then this should fix it and close #6.

Don't use Vercel myself. I presume you can set the node version similarly there.

### CODE REVIEW

**Comment by kwaa** [comment]
Setting `NODE_VERSION` doesn't seem to work.
Since this is a serverless function, it appears to be related to `AWS_LAMBDA_FUNCTION_VERSION`; but it currently only supports up to `nodejs14.x`.
So I'll fix it with a hard reset, but thanks anyway for contributing!

**Comment by janosh** [comment]
Ah, then I misunderstood you. I thought you were saying the build was failing, not at run time. But then why not always use the static adapter for this demo site? Are you actually using a lambda for anything? If not, let the browser run your code since most support `array.at()` (see MDN docs linked above).

**Comment by kwaa** [comment]
> Ah, then I misunderstood you. I thought you were saying the build was failing, not at run time. But then why not always use the static adapter for this demo site? Are you actually using a lambda for anything? If not, let the browser run your code since most support `array.at()` (see MDN docs linked above).

Hmm... mainly I don't quite understand how to set the function to execute only with the browser. write it after `if(browser) {` ?
Maybe it's possible to set the toc component to be called only when `browser === true`.

**Comment by janosh** [comment]
Exactly, or wrap it in `onMount`/`afterNavigate`. That's what I did in [`svelte-toc`](https://github.com/janosh/svelte-toc/blob/7aa4f048a80af7c90b21fee04304e23ac8c06bd3/src/lib/Toc.svelte#L28-L37).

**Comment by kwaa** [comment]
👍 Thanks for the suggestion, now the toc is only displayed on the browser side.

**Pull request closed without merging**
