### PR TITLE
feat: ✨ add project page

### PR DESCRIPTION
**Pull request by Sevichecc**
A page template for projects.
Demo:https://seviche.cc/projects

### CODE REVIEW

**Comment by kwaa** [comment]
🤔 Nice work, but - Urara exercises restraint in adding such features and recommends that users who need them implement them themselves: so this will not be merged. (just like my blog's friends page)

The only exception to this is the addition of common post types that are listed in the [IndieWeb Wiki](https://indieweb.org/posts#Types_of_Posts) but not yet supported by Urara.

**Comment by Sevichecc** [comment]
A repo for the Urara use cases might be very helpful 🤔, or a dev branch.

Just some random thoughts...

**Comment by kwaa** [comment]
> A repo for the Urara use cases might be very helpful 🤔, or a dev branch.
> 
> Just some random thoughts...

I think maybe it could be shown as a variant in README.md?

**Comment by Sevichecc** [comment]
> > A repo for the Urara use cases might be very helpful 🤔, or a dev branch.
> > Just some random thoughts...
> 
> I think maybe it could be shown as a variant in README.md?

That would be nice!

**Comment by kwaa** [comment]
Finished.
btw, you can add the `urara-blog` topic to your own repo.

**Pull request closed without merging**
