### PR TITLE
docs(readme): 📝 add site that uses urara

### PR DESCRIPTION
**Pull request by kwchang0831**

### CODE REVIEW

**Comment by kwaa** [comment]
urara.kwchang0831.dev will updates be kept?

**Comment by kwchang0831** [comment]
Yes.

**Comment by kwaa** [comment]
> Yes.

After a month, apparently urara.kwchang0831.dev is not updated:

- [plausible](https://www.kwchang0831.dev/plausible)

**Comment by kwchang0831** [comment]
I am sorry.

**Comment by kwchang0831** [comment]
Since I cannot update my blog that uses Urara in a timely manner, I understand that I am no longer qualified to be listed on the [Urara README #Sites](https://github.com/importantimport/urara#-sites).

I am sorry. Please accept the PR #38 to remove my site.
Thanks.

**Pull request merged**
